# Specify your own secret
# Following example uses ExternalSecret provided by Vault
# apiVersion: kubernetes-client.io/v1
# kind: ExternalSecret
# metadata:
#   name: {{ .Values.externalSecretName }}
# spec:
#   backendType: vault
#   template:
#     type: kubernetes.io/tls
#   data:
#     - key: your-tls-crt-path
#       name: tls.crt
#       property: public_key
#     - key: your-tls-key-path
#       name: tls.key
#       property: private_key
#     - key: your-encryption-key-path
#       name: encryption-key
#       property: encryption-key
#     - key: your-jwt-secret-path
#       name: jwt-secret
#       property: jwt-secret
#     - key: your-mongo-connection-uri-path
#       name: mongo-connection-uri
#       property: mongo-connection-uri
#     - key: your-mongo-root-password-path
#       name: mongodb-root-password
#       property: mongodb-root-password
#   kvVersion: 2
#   vaultMountPoint: your-vault-mount-point
#   vaultRole: external-secrets
